-- ============================================================================
-- VERITAS ER / RECONCILE.AI — College Student Entity Resolution Schema
-- Target Database: Supabase PostgreSQL
-- ============================================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- ----------------------------------------------------------------------------
-- 1. SOURCES TABLE
-- Tracks input data origins (e.g., ERP, Placement, Hostel, Library, Alumni)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sources (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    source_name VARCHAR(100) UNIQUE NOT NULL,
    description TEXT,
    reliability_score NUMERIC(3, 2) NOT NULL DEFAULT 0.80 CHECK (reliability_score >= 0.0 AND reliability_score <= 1.0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- 2. RAW STUDENTS TABLE
-- Stores original raw record payloads ingested from various college systems
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS raw_students (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    source_id UUID NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
    
    -- College Student Core Attributes
    reg_no VARCHAR(50),              -- e.g., 2021BTCS042, 21BCE0192
    dob DATE,                        -- Date of Birth (YYYY-MM-DD)
    name VARCHAR(255) NOT NULL,      -- Student Full Name
    branch VARCHAR(100),             -- e.g., CSE, ECE, Mechanical, IT
    course VARCHAR(100),             -- e.g., B.Tech, M.Tech, BCA, MCA
    email VARCHAR(255),              -- College or Personal Email
    phone_number VARCHAR(20),        -- Phone Number with/without country code
    
    -- Raw and Normalized Payloads
    raw_payload JSONB NOT NULL,       -- Original untouched JSON payload
    normalized_payload JSONB,        -- Standardized values (lowercase, stripped spaces, etc.)
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- 3. MASTER STUDENTS TABLE (Golden Record / Single Source of Truth)
-- Reconciled master student profile generated by automated or human triage
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS master_students (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    
    -- Golden Student Core Attributes
    golden_reg_no VARCHAR(50) UNIQUE,
    golden_name VARCHAR(255) NOT NULL,
    golden_dob DATE,
    golden_branch VARCHAR(100),
    golden_course VARCHAR(100),
    golden_email VARCHAR(255),
    golden_phone_number VARCHAR(20),
    
    -- Quality & Triage Metrics
    confidence_score NUMERIC(3, 2) NOT NULL DEFAULT 1.00 CHECK (confidence_score >= 0.0 AND confidence_score <= 1.0),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'MERGED', 'FLAGGED', 'ARCHIVED')),
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- 4. STUDENT ENTITY LINKS TABLE
-- Maps raw incoming student records to their resolved Master Record
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS student_entity_links (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    raw_student_id UUID NOT NULL REFERENCES raw_students(id) ON DELETE CASCADE,
    master_student_id UUID NOT NULL REFERENCES master_students(id) ON DELETE CASCADE,
    match_score NUMERIC(3, 2) NOT NULL CHECK (match_score >= 0.0 AND match_score <= 1.0),
    link_type VARCHAR(30) NOT NULL CHECK (link_type IN ('AUTO_MATCH', 'MANUAL_APPROVAL', 'INITIAL_INGESTION')),
    linked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(raw_student_id, master_student_id)
);

-- ----------------------------------------------------------------------------
-- 5. STUDENT CONFLICT QUEUE TABLE (Human-in-the-Loop Triage)
-- Stores ambiguous candidate pairs (Confidence score between 0.60 and 0.89)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS student_conflict_queue (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    record_1_id UUID NOT NULL REFERENCES raw_students(id) ON DELETE CASCADE,
    record_2_id UUID NOT NULL REFERENCES raw_students(id) ON DELETE CASCADE,
    
    match_confidence NUMERIC(3, 2) NOT NULL CHECK (match_confidence >= 0.0 AND match_confidence <= 1.0),
    field_diffs JSONB NOT NULL,         -- JSON object comparing conflicting fields
    llm_reasoning TEXT,                 -- Explanation generated by Gemini LLM Arbitrator
    
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'EDITED')),
    assigned_reviewer VARCHAR(100),
    resolved_by VARCHAR(100),
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- 6. STUDENT AUDIT LEDGER TABLE (Cryptographic SHA-256 Hash Chaining)
-- Tamper-evident ledger logging every change to a student master profile
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS student_audit_ledger (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    master_student_id UUID REFERENCES master_students(id) ON DELETE SET NULL,
    action_type VARCHAR(50) NOT NULL,    -- CREATE, AUTO_MERGE, MANUAL_RESOLVE, FIELD_OVERRIDE
    payload JSONB NOT NULL,              -- State of record at this audit point
    previous_hash VARCHAR(64) NOT NULL,  -- SHA-256 hash of previous block (H_{n-1})
    current_hash VARCHAR(64) NOT NULL,   -- SHA-256 hash of current block (H_n)
    performed_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- INDEXES & PERFORMANCE OPTIMIZATION
-- ============================================================================

-- Exact Lookup Indexes
CREATE INDEX IF NOT EXISTS idx_raw_students_reg_no ON raw_students(reg_no);
CREATE INDEX IF NOT EXISTS idx_raw_students_email ON raw_students(email);
CREATE INDEX IF NOT EXISTS idx_raw_students_phone ON raw_students(phone_number);
CREATE INDEX IF NOT EXISTS idx_raw_students_dob ON raw_students(dob);

CREATE INDEX IF NOT EXISTS idx_master_students_reg_no ON master_students(golden_reg_no);
CREATE INDEX IF NOT EXISTS idx_master_students_email ON master_students(golden_email);

-- Trigram Similarity (GIN) Indexes for Fuzzy Text Search (Names & Emails)
CREATE INDEX IF NOT EXISTS idx_raw_students_name_trgm ON raw_students USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_raw_students_email_trgm ON raw_students USING gin (email gin_trgm_ops);

-- Conflict Queue Status Index
CREATE INDEX IF NOT EXISTS idx_conflict_queue_status ON student_conflict_queue(status);
